#==========================================================================
# Description: Build Image For EA_3588S
#==========================================================================

name: Build Image For EA_3588S

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "Select OS Release."
        required: true
        default: "noble"
        type: choice
        options:
          - jammy
          - noble
          - bookworm
          - bullseye
      set_kernel:
        description: "Select kernel version"
        required: true
        default: "5.10.226"
        type: choice
        options:
          - 5.10.110
          - 5.10.226
          - 6.1.115
      set_desktop:
        description: "Set desktop type"
        required: true
        default: "cli"
        type: choice
        options:
          - cli
          - xfce
          - gnome

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q) 2>/dev/null
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install python2 python2-dev python-is-python3 squashfs-tools rar $(curl -fsSL https://tinyurl.com/ubuntu2204-build-armbian)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo timedatectl set-timezone "${TZ}"
          # init output prefix  ${{ steps.init.outputs.build_tag }}
          echo "build_tag=Armbian_EA-3588S_${{ inputs.set_release }}_${{ inputs.set_kernel }}_${{ inputs.set_desktop }}" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create simulated physical disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner.runner /builder
          df -Th

      - name: Download Git Repository
        id: down_d3588
        working-directory: /builder/
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          df -hT ${PWD}
          git clone --recursive --single-branch --branch=master https://github.com/yifengyou/ea_3588s.git ea_3588s.git
          ls -alh ea_3588s.git
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile u-boot-v2017 for EA-3588S
        id: compile_d3588_uboot
        working-directory: /builder/ea_3588s.git/u-boot-v2017
        if: ${{ steps.copy_template.outputs.status }} == 'success' && !cancelled()
        run: |
          ./ea_3588s.sh
          md5sum ../rockdev/uboot.img
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile Kernel for EA-3588S
        id: compile_d3588_kernel
        working-directory: /builder/ea_3588s.git
        if: ${{ steps.compile_d3588_uboot.outputs.status }} == 'success' && !cancelled()
        run: |
          cd kernel-${{ inputs.set_kernel }}
          ./ea_3588s.sh
          md5sum ../rockdev/boot.img
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Download armbian source code
        id: down_armbian
        working-directory: /builder/
        if: ${{ steps.compile_d3588_kernel.outputs.status }} == 'success' && !cancelled()
        run: |
          set -x
          git clone -q --single-branch \
          --depth=1 \
          --branch=main \
          https://github.com/armbian/build.git armbian.git
          ls -alh armbian.git
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile Armbian [ ${{ inputs.set_release }} ] [ ${{ inputs.set_desktop }} ]
        id: compile_armbian
        working-directory: /builder/armbian.git
        if: ${{ steps.down_armbian.outputs.status }} == 'success' && !cancelled()
        run: |
          if [ "${{ inputs.set_desktop }}" == "cli" ] ; then
          BUILD_DESKTOP="BUILD_DESKTOP=no"
          else
          BUILD_DESKTOP=" \
                         BUILD_DESKTOP=yes \
                         DESKTOP_APPGROUPS_SELECTED=remote_desktop \
                         DESKTOP_ENVIRONMENT=${{ inputs.set_desktop }} \
                         DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base"
                         fi
                         # BRANCH=edge    : newest kernel such as 6.10
                         # BRANCH=current : stable kernel such as 6.6
                         # BRANCH=legacy  : vendor kernel rockchip 5.10
                         ./compile.sh RELEASE=${{ inputs.set_release }} \
                         BOARD=nanopct6 \
                         BRANCH=current\
                         BUILD_MINIMAL=no \
                         BUILD_ONLY=default \
                         HOST=armbian \
                         ${BUILD_DESKTOP} \
                         EXPERT=yes \
                         KERNEL_CONFIGURE=no \
                         COMPRESS_OUTPUTIMAGE="sha,img,xz" \
                                                          VENDOR="Armbian" \
                                                                          SHARE_LOG=yes
                                                                          ls -alh /builder/armbian.git/output/images/
                                                                          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Extract rootfs from Armbian
        id: extract_rootfs
        working-directory: /builder/ea_3588s.git
        if: ${{ steps.compile_armbian.outputs.status }} == 'success' && !cancelled()
        run: |
          chmod +x /builder/ea_3588s.git/scripts/extract-rootfs-from-armbian.sh
          /builder/ea_3588s.git/scripts/extract-rootfs-from-armbian.sh /builder/armbian.git/output/images/
          ls -alh /builder/armbian.git/output/images/rootfs.img
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Hack rootfs
        id: hack_rootfs
        working-directory: /builder/armbian.git/output/images/
        if: ${{ steps.extract_rootfs.outputs.status }} == 'success' && !cancelled()
        run: |
          # hack rootfs, must start with sudo
          sudo mount rootfs.img /mnt
          # sudo bash -c 'echo "tmpfs /tmp tmpfs defaults,nosuid 0 0" >> /mnt/etc/fstab'
          sync
          sudo umount /mnt
          mkdir -p /builder/ea_3588s.git/release
          mv /builder/armbian.git/output/images/rootfs.img /builder/ea_3588s.git/ouput-temp/
          cd /builder/ea_3588s.git/ouput-temp/
          mksquashfs rootfs.img  /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rootfs.img.squashfs
          sha256sum /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rootfs.img.squashfs > \
          /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rootfs.img.squashfs.sha256
          rar a /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rootfs.img.rar rootfs.img
          sha256sum /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rootfs.img.rar > \
          /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rootfs.img.rar.sha256
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Generate updatable image
        id: generate_updateable_image
        working-directory: /builder/ea_3588s.git/
        if: ${{ steps.hack_rootfs.outputs.status }} == 'success' && !cancelled()
        run: |
          # rootfs.img   : /builder/ea_3588s.git/ouput-temp/rootfs.img
          # uboot.img    : /builder/ea_3588s.git/ouput-temp/uboot.img
          # boot.img     : /builder/ea_3588s.git/ouput-temp/boot.img
          # RKDevTool    : /builder/ea_3588s.git/tools/RKDevTool
          # afptool      : /builder/ea_3588s.git/tools/afptool
          # rkImageMaker : /builder/ea_3588s.git/tools/rkImageMaker
          # template     : /builder/ea_3588s.git/ouput-temp

          mkdir -p /builder/ea_3588s.git/release
          mkdir -p /builder/ea_3588s.git/output-updatable-image
          # copy RKDevTool
          cp -a /builder/ea_3588s.git/tools/RKDevTool /builder/ea_3588s.git/output-updatable-image/
          mkdir -p /builder/ea_3588s.git/output-updatable-image/RKDevTool/rockdev/image/
          # copy template
          cp -a  /builder/ea_3588s.git/ouput-temp/* \
          /builder/ea_3588s.git/output-updatable-image/RKDevTool/rockdev/image/

          chmod +x /builder/ea_3588s.git/tools/afptool
          chmod +x /builder/ea_3588s.git/tools/rkImageMaker
          cd /builder/ea_3588s.git/output-updatable-image/RKDevTool/rockdev/image/
          /builder/ea_3588s.git/tools/afptool -pack . temp.img
          /builder/ea_3588s.git/tools/rkImageMaker -RK3588 MiniLoaderAll.bin temp.img update.img -os_type:androidos
          find . -type f ! -name "update.img" -exec rm -f {} \;

          # generate update.img
          cd /builder/ea_3588s.git/output-updatable-image/
          mksquashfs RKDevTool  /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_update.img.squashfs && \
          rar a /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_update.img.rar RKDevTool
          sha256sum /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_update.img.squashfs > \
          /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_update.img.squashfs.sha256
          sha256sum /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_update.img.rar > \
          /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_update.img.rar.sha256

      - name: Generate rockdev image
        id: generate_rockdev_image
        working-directory: /builder/ea_3588s.git/
        if: ${{ steps.generate_updateable_image.outputs.status }} == 'success' && !cancelled()
        run: |
          # rootfs.img   : /builder/ea_3588s.git/ouput-temp/rootfs.img
          # uboot.img    : /builder/ea_3588s.git/ouput-temp/uboot.img
          # boot.img     : /builder/ea_3588s.git/ouput-temp/boot.img
          # RKDevTool    : /builder/ea_3588s.git/tools/RKDevTool
          # afptool      : /builder/ea_3588s.git/tools/afptool
          # rkImageMaker : /builder/ea_3588s.git/tools/rkImageMaker
          # template     : /builder/ea_3588s.git/ouput-temp

          mkdir -p /builder/ea_3588s.git/release
          mkdir -p /builder/ea_3588s.git/output-rockdev-image
          # copy RKDevTool
          cp -a /builder/ea_3588s.git/tools/RKDevTool /builder/ea_3588s.git/output-rockdev-image/
          mkdir -p /builder/ea_3588s.git/output-rockdev-image/RKDevTool/rockdev/image/
          # copy template
          cp -a  /builder/ea_3588s.git/ouput-temp/* \
          /builder/ea_3588s.git/output-rockdev-image/RKDevTool/rockdev/image/

          # generate rockdev.img
          cd /builder/ea_3588s.git/output-rockdev-image/
          mksquashfs RKDevTool  /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rockdev.img.squashfs && \
          rar a /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rockdev.img.rar RKDevTool
          sha256sum /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rockdev.img.squashfs > \
          /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rockdev.img.squashfs.sha256
          sha256sum /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rockdev.img.rar > \
          /builder/ea_3588s.git/release/${{ steps.init.outputs.build_tag }}_rockdev.img.rar.sha256
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload Image to Release
        uses: ncipollo/release-action@main
        if: ${{ steps.generate_rockdev_image.outputs.status }} == 'success' && !cancelled()
        with:
          tag: Armbian_EA-3588S_Image_${{ inputs.set_kernel }}
          artifacts: /builder/ea_3588s.git/release/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### EA-3588S镜像说明

            1. 镜像命名规则
            以 * Armbian_EA-3588S_noble_5.10.226_cli_01_rockdev.img.rar** 为例

      - "Armbian_EA-3588S" 固定前缀
      - "noble" 发行版，可选 (jammy,noble,bookworm,bullseye)
      - "5.10.226" 内核版本号，可选 (5.10.110,5.10.226,6.1.115)
      - "cli" 桌面环境，可选 (cli,xfce,gnome)
      - "01" 镜像模板，对应名称如下
      - (01) "GB_A588_ubuntu22.04.5_20250517_180656_xfce4-v01"
      - (02) "A588_ubuntu20.04_20230202-135921_V1.0"
      - (03) "GB-RK3588-ubuntu20.04-20250610-105959-V1.38-ALL-A-CM"
      - (04) "rk3588_linux_openSdk"
      - "rockdev" 镜像类型，包括一下三种类型
      - rockdev: RKDevTool + 多个小image镜像（uboot.img、boot.img、rootfs.img等）
      - update : RKdevTool + update.img
      - rootfs : 仅rootfs镜像

        2. 系统密码

      - 默认用户名(Default username): root
      - 默认密码(Default password): 123

        3. rockdev构建输出(rockdev.squashfs/rockdev.rar)

        带windows更新工具RKDevTool，开箱即用。包含以下目录结构，windows下载后解压，执行RKDevTool.exe即可。
        ```
        RKDevTool/
        ├── bin
        │         ├── adb.exe
        │         ├── AdbWinApi.dll
        │         ├── AdbWinUsbApi.dll
        │         ├── AFPTool.exe
        │         └── RKImageMaker.exe
        ├── config.cfg
        ├── config.ini
        ├── Language
        │         ├── Chinese.ini
        │         └── English.ini
        ├── RKDevTool.exe
        └── rockdev
        └── image
        ├── boot.img
        ├── MiniLoaderAll.bin
        ├── misc.img
        ├── modules.tar.gz
        ├── oem.img
        ├── package-file
        ├── parameter.txt
        ├── recovery.img
        ├── rootfs.img
        └── uboot.img
        ```

        4. update镜像构建输出(update.img.squashfs/update.img.rar)

        解压后输出update.img镜像，请使用 RKDevTool.exe 固件更新

        ```
        RKDevTool/
        ├── bin
        │         ├── adb.exe
        │         ├── AdbWinApi.dll
        │         ├── AdbWinUsbApi.dll
        │         ├── AFPTool.exe
        │         └── RKImageMaker.exe
        ├── config.cfg
        ├── config.ini
        ├── Language
        │         ├── Chinese.ini
        │         └── English.ini
        ├── RKDevTool.exe
        └── rockdev
        └── image
        └── update.img
        ```
